### ISSUE TITLE
practica de funciones 

### ISSUE THREAD

**Issue by elisa1223** [SistemasTecTlaxiaco/actividad-6-practica-de-relaciones-equipo-nestor-diego-elisa#2]
[elisa_sanchez_coronel_practica.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-relaciones-equipo-nestor-diego-elisa/files/12826119/elisa_sanchez_coronel_practica.pdf)

**Comment by bibiana-m** [comment]
portada 25%
procedimiento 25%
figuras 25%
resultados 25%
total 100% de 20 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
