### ISSUE TITLE
PRACTICA FUNCIONES NESTOR  CRUZ LEON

### ISSUE THREAD

**Issue by Nestor283** [SistemasTecTlaxiaco/actividad-6-practica-de-relaciones-equipo-nestor-diego-elisa#3]
[PRACTICA_MATEMATICAS_ DISCRETAS_NESTOR_CRUZ_LEON..pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-relaciones-equipo-nestor-diego-elisa/files/12826122/PRACTICA_MATEMATICAS_.DISCRETAS_NESTOR_CRUZ_LEON.pdf)

**Comment by bibiana-m** [comment]
portada 25%
procedimiento 25%
figuras 25%
resultados 25%
total (100%)/100*20 = 20

Bien hecho!

**Comment by josealfredo79** [comment]
Revisado..
